/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_test_JniDemo */

#ifndef _Included_com_test_JniDemo
#define _Included_com_test_JniDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_test_JniDemo
 * Method:    getStringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_test_JniDemo_getStringFromC
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
